INSERT INTO units (unit) VALUES ('安檢大隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('安檢大隊', '第一隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('安檢大隊', '第二隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('安檢大隊', '第三隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('安檢大隊', '第四隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('安檢大隊', '第五隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('安檢大隊', '第六隊');
--;;
INSERT INTO units (unit) VALUES ('保安大隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('保安大隊', '第1隊第1分隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('保安大隊', '第1隊第2分隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('保安大隊', '第1隊第3分隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('保安大隊', '第2隊第1分隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('保安大隊', '第2隊第2分隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('保安大隊', '第2隊第3分隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('保安大隊', '第3隊第1分隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('保安大隊', '第3隊第2分隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('保安大隊', '第3隊第3分隊');
--;;
INSERT INTO units (unit) VALUES ('刑警大隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('刑警大隊', '偵一隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('刑警大隊', '偵二隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('刑警大隊', '偵三隊');
--;;
INSERT INTO units (unit) VALUES ('臺北分局');
--;;
INSERT INTO units (unit, subunit) VALUES ('臺北分局', '安檢隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('臺北分局', '警備隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('臺北分局', '金門所');
--;;
INSERT INTO units (unit, subunit) VALUES ('臺北分局', '花蓮所');
--;;
INSERT INTO units (unit, subunit) VALUES ('臺北分局', '臺東所');
--;;
INSERT INTO units (unit, subunit) VALUES ('臺北分局', '南竿所');
--;;
INSERT INTO units (unit, subunit) VALUES ('臺北分局', '綠島所');
--;;
INSERT INTO units (unit, subunit) VALUES ('臺北分局', '蘭嶼所');
--;;
INSERT INTO units (unit, subunit) VALUES ('臺北分局', '北竿所');
--;;
INSERT INTO units (unit) VALUES ('高雄分局');
--;;
INSERT INTO units (unit, subunit) VALUES ('高雄分局', '安檢隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('高雄分局', '警備隊');
--;;
INSERT INTO units (unit, subunit) VALUES ('高雄分局', '臺中所');
--;;
INSERT INTO units (unit, subunit) VALUES ('高雄分局', '嘉義所');
--;;
INSERT INTO units (unit, subunit) VALUES ('高雄分局', '臺南所');
--;;
INSERT INTO units (unit, subunit) VALUES ('高雄分局', '恆春所');
--;;
INSERT INTO units (unit, subunit) VALUES ('高雄分局', '馬公所');
--;;
INSERT INTO units (unit, subunit) VALUES ('高雄分局', '七美所');
--;;
INSERT INTO units (unit, subunit) VALUES ('高雄分局', '望安所');
--;;
INSERT INTO units (unit) VALUES ('勤指中心');
--;;
INSERT INTO units (unit) VALUES ('航空保安科');